### ISSUE TITLE
Magento 2 Support

### ISSUE THREAD

**Issue by williamjulianvicary** [webgriffe/server-google-analytics-extension#1]
Hey there,

It's not particularly clear, but I believe this is an M1 extension... This is exactly what I'm looking for but before I start recreating the wheel, do you by any chance have a M2 version or know if this version will work with M2?

Thanks

Will

**Comment by azambon** [comment]
Hello,

you're right, this is an M1 extension, and it will not work with M2. We should really add a readme :)

And no, unfortunately we don't have an equivalent for M2 of this extension. Sorry.
